const list = [
  {
    id: 1,
    title: 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops',
    description:
      'Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday',
    category: "men's clothing",
    image: '../Images/img-1.webp',
    rating: ' 1.6 🌟',
    quantity: '23',
    size: 'L',
    stock: '😃in-stock',
    price: 35,
    amount: 1,
  },
  {
    id: 2,
    title: 'Mens Casual Premium Slim Fit T-Shirts ',
    price: 22,
    description:
      'Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a three-button placket.',
    category: "men's clothing",
    image: '../Images/img-2.jpg',
    rating: ' 1.8 🌟',
    quantity: '3',
    size: 'L',
    stock: '😃in-stock',
    amount: 1,
  },
  {
    id: 3,
    title: 'Mens Cotton Jacket',
    description:
      'great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoo. Good gift choice for you or your family member. A warm hearted love to Father, husband or son in this thanksgiving or Christmas Day.',
    category: "men's clothing",
    image: '../Images/img-3.jpg',
    rating: ' 4.8 🌟',
    quantity: '11',
    size: 'L',
    stock: 'in-stock 😃',
    price: 60,
    amount: 1,
  },
  {
    id: 4,
    title: 'Mens Casual Slim Fit',
    description:
      'The color could be slightly different between on the screen and in practice. / Please note that body builds vary by peon, therefore, detailed size information should be reviewed below on the product description.',
    category: "men's clothing",
    image: '../Images/img-4.jpg',
    rating: ' 4.6 🌟',
    quantity: '9',
    size: 'XL',
    stock: 'in-stock 😃',
    price: 48,
    amount: 1,
  },
  {
    id: 5,
    title:
      "John Hardy Women's Legends Naga Gold & Silver Dragon Station Chain Bracelet",
    description:
      "From our Legends Collection, the Naga was inspired by the mythical water dragon that protects the ocean's pearl. Wear facing inward to be bestowed with love and abundance, or outward for protection.",
    category: 'jewelery',
    image: '../Images/img-5.jpg',
    rating: ' 2.6 🌟',
    quantity: '4',
    size: 'XL',
    stock: 'in-stock 😃',
    price: 15,
    amount: 1,
  },
  {
    id: 6,
    title: 'Solid Gold Petite Micropave ',
    description:
      'Satisfaction Guaranteed. Return or exchange any order within 30 days.Designed and sold by Hafeez Center in the United States. Satisfaction Guaranteed. Return or exchange any order within 30 days.',
    category: 'jewellery',
    image: '../Images/img-6.jpg',
    rating: ' 1.8 🌟',
    quantity: '2',
    size: 'M',
    stock: 'in-stock 😃',
    price: 75,
    amount: 1,
  },
  {
    id: 7,
    title: 'White Gold Plated Princess',
    price: 45,
    description:
      "Classic Created Wedding Engagement Solitaire Diamond Promise Ring for Her. Gifts to spoil your love more for Engagement, Wedding, Anniveary, Valentine's Day...",
    category: 'jewellery',
    image: '../Images/img-7.jpg',
    rating: ' 1.9 🌟',
    quantity: '9',
    size: 'M',
    stock: 'in-stock 😃',
    amount: 1,
  },
  {
    id: 8,
    title: 'Pierced Owl Rose Gold Plated Stainless Steel Double',
    price: 85,
    description:
      'Rose Gold Plated Double Flared Tunnel Plug Earrings. Made of 316L Stainless Steel',
    category: 'jewellery',
    image: '../Images/img-8.jpg',
    rating: ' 1.6 🌟',
    quantity: '13',
    size: 'S',
    stock: 'in-stock 😃',
    amount: 1,
  },
  {
    id: 9,
    title: 'WD 2TB Elements Portable External Hard Drive - USB 3.0 ',
    price: 15,
    description:
      'USB 3.0 and USB 2.0 Compatibility Fast data transfe Improve PC Performance High Capacity; Compatibility Formatted NTFS for Windows 10, Windows 8.1, Windows 7; Reformatting may be required for other operating systems; Compatibility may vary depending on user’s hardware configuration and operating system',
    category: 'electronics',
    image: '../Images/img-9.jpg',
    rating: ' 4.6 🌟',
    quantity: '17',
    size: '300cm',
    stock: 'in-stock 😃',
    amount: 1,
  },

  {
    id: 10,
    title: 'Acer SB220Q bi 21.5 inches Full HD (1920 x 1080) IPS Ultra-Thin',
    price: 105,
    description:
      '21. 5 inches Full HD (1920 x 1080) widescreen IPS display And Radeon free Sync technology. No compatibility for VESA Mount Refresh  75Hz - Using HDMI port Zero-frame design | ultra-thin | 4ms response time | IPS panel Aspect ratio - 16: 9. Color Supported - 16. 7 million colo. Brightness - 250 nit Tilt angle -5 degree to 15 degree. Horizontal viewing angle-178 degree. Vertical viewing angle-178 degree 75 hertz',
    category: 'electronics',
    image: '../Images/img-11.jpg',
    rating: ' 3.1 🌟',
    quantity: '7',
    size: '220cm',
    stock: '🥺out-of-stock',
    amount: 1,
  },

  {
    id: 11,
    title: "BIYLACLESEN Women's 3-in-1 Snowboard Jacket Winter Coats",
    price: 15.9,
    description:
      'Note:The Jackets is US standard size, Please choose size as your usual wear Material: 100% Polyester; Detachable Liner Fabric: Warm Fleece. Detachable Functional Liner: Skin Friendly, Lightweigt and Warm.Stand Collar Liner jacket, keep you warm in cold weather. Zippered Pockets: 2 Zippered Hand Pockets, 2 Zippered Pockets on Chest (enough to keep cards or keys)and 1 Hidden Pocket Inside.Zippered Hand Pockets and Hidden Pocket keep your things secure. Humanized Design: Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and water,for a comfortable fit. 3 in 1 Detachable Design provide more convenience, you can sepaprice the coat and inner as needed, or wear it together. It is suitable for different season and help you adapt to different climates',
    category: "women's clothing",
    image: '../Images/img-13.jpg',
    rating: ' 4.1 🌟',
    quantity: '12',
    size: 'S',
    stock: '🥺out-of-stock',
    amount: 1,
  },
  {
    id: 12,
    title:
      "Lock and Love Women's Removable Hooded Faux Leather Moto Biker Jacket",
    price: 13.0,
    description:
      '100% POLYURETHANE(shell) 100% POLYESTER(lining) 75% POLYESTER 25% COTTON (SWEATER), Faux leather material for style and comfort / 2 pockets of front, 2-For-One Hooded denim style faux leather jacket, Button detail on waist / Detail stitching at sides, HAND WASH ONLY / DO NOT BLEACH / LINE DRY / DO NOT IRON',
    category: "women's clothing",
    image: '../Images/img-14.jpg',
    rating: ' 4.3 🌟',
    quantity: '6',
    size: 'M',
    stock: '😃in-stock',
    amount: 1,
  },
  {
    id: 13,
    title: 'Rain Jacket Women Windbreaker Striped Climbing Raincoats',
    price: 39.99,
    description:
      "Lightweight perfet for trip or casual wear---Long sleeve with hooded, adjustable drawstring waist design. Button and zipper front closure raincoat, fully stripes Lined and The Raincoat has 2 side pockets are a good size to hold all kinds of things, it cove the hips, and the hood is generous but doesn't overdo it.Attached Cotton Lined Hood with Adjustable Drawstrings give it a real styled look.",
    category: "women's clothing",
    image: '../Images/img-15.jpg',
    rating: ' 4.6 🌟',
    quantity: '8',
    size: 'M',
    stock: '😃in-stock',
    amount: 1,
  },
  {
    id: 14,
    title: "MBJ Women's Solid Short Sleeve Boat Neck V ",
    price: 25,
    description:
      '95% RAYON 5% SPANDEX, Made in USA or Imported, Do Not Bleach, Lightweight fabric with great stretch for comfort, Ribbed on sleeves and neckline / Double stitching on bottom hem',
    category: "women's clothing",
    image: '../Images/img-16.jpg',
    rating: ' 3.9 🌟',
    quantity: '54',
    size: 'L',
    stock: '😃in-stock',
    amount: 1,
  },
  {
    id: 15,
    title: "Opna Women's Short Sleeve Moisture",
    price: 75,
    description:
      '100% Polyester, Machine wash, 100% cationic polyester interlock, Machine Wash & Pre Shrunk for a Great Fit, Lightweight, roomy and highly breathable with moisture wicking fabric which helps to keep moisture away, Soft Lightweight Fabric with comfortable V-neck collar and a slimmer fit, delive a sleek, more feminine silhouette and Added Comfort',
    category: "women's clothing",
    image: '../Images/img-17.jpg',
    rating: ' 3.7 🌟',
    quantity: '27',
    size: 'XL',
    stock: '😃in-stock',
    amount: 1,
  },
  {
    id: 16,
    title: 'DANVOUY Womens T Shirt Casual Cotton Short',
    price: 46.03,
    description:
      '95%Cotton,5%Spandex, Features: Casual, Short Sleeve, Letter Print,V-Neck,Fashion Tees, The fabric is soft and has some stretch., Occasion: Casual/Office/Beach/School/Home/Street. Season: Spring,Summer,Autumn,Winter.',
    category: "women's clothing",
    image: '../Images/img-18.jpg',
    rating: ' 3.6 🌟',
    quantity: '3',
    size: 'L',
    stock: 'in-stock 😃',
    amount: 1,
  },
];

export default list;
